sonar.projectKey=ECI-Maestria_sentinel-health-engine-be
sonar.organization=eci-maestria-mobile

sonar.projectName=Sentinel Health Engine - Backend
sonar.projectVersion=1.0

sonar.sources=services/telemetry-service,services/health-rules-service,services/alerts-service
sonar.exclusions=**/cmd/**,**/infrastructure/**,**/*_test.go

sonar.tests=services/telemetry-service,services/health-rules-service,services/alerts-service
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage/telemetry.out,coverage/health-rules.out,coverage/alerts.out

sonar.sourceEncoding=UTF-8
